package observer;

import model.UserRole;

/**
 * concrete Observer class for the Inventory Manager role.
 *
 * implements the StockObserver interface to receive notifications
 * related to stock level changes and purchase orders.
 *
 * alerts generated by this observer are intended for Inventory Managers only.
 */
public class InventoryManagerObserver implements StockObserver {

    /**
     * handles the notification message when stock changes occur.
     *
     * @param message the notification message.
     */
    @Override
    public void update(String message) {
        System.out.println("Inventory Manager Alert: " + message);
    }

    /**
     * returns the user role associated with this observer.
     * used for role-based notification filtering.
     *
     * @return UserRole.INVENTORY_MANAGER
     */
    @Override
    public UserRole getRole() {
        return UserRole.INVENTORY_MANAGER;
    }
}